version: '3.8'
services:
  db:
    image: postgres:14.4-alpine
    ports:
      - ${DB_PORT}:5433
    networks:
      - lumi-net
    restart: always
    volumes:
      - ./:/lumi
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    command: -p 5433
  redis:
    image: redis:7.0.2-alpine
    networks:
      - lumi-net
    restart: always
  api:
    image: lumi-api
    build:
      dockerfile: ./src/Dockerfile
      context: .
      target: dev
    networks:
      - lumi-net
    volumes:
      - .:/lumi/app
      - /lumi/app/node_modules
    ports:
      - ${APP_PORT}:3001
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: npm run start:dev app
networks:
  lumi-net:
    driver: bridge
